pipeline {
    agenty any

    stages {
      stage ('Code Checkout') {
        steps {
          checkout scm
        }
      }

      stage ('Build') {
        steps {
          sh 'docker build -t helloworld:latest -f helloworld/Dockerfile .'
        }
      }

      stage ('Deploy') {
        steps {
          sh 'docker run helloworld:latest -p 3000:3000'
        }
      }
    }
}
